# Generated by Django 2.1.3 on 2018-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_confirmation', '0002_auto_20180714_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneconfirmation',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
